dependencies:
- name: sms-demo-faststart
  version: 0.0.1
  repository: https://artifactory-tools.garage-dev-ocp3-c-460849-0143c5dd31acd8e030a1d6e0ab1380e3-0001.us-east.containers.appdomain.cloud/artifactory/generic-local/garage-dev-tools
