dependencies:
- name: sms-demo-01
  version: 1.0.0-7
  repository: https://artifactory-tools.garage-dev-ocp4-c-496764-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/garage-dev-tools/sms-demo-01-1.0.0-7.tgz
